import { Button, Grid } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Products from './products'

export default function Home() {
  // console.log("Title", title)
  return (
     <div className={styles.container}>
      <Head>
       
        {/* <title>{title? `${title}-Ecommerce App`: 'Ecommerce App'}</title> */}
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container spacing={3}>
        <Products />
      </Grid>
    </div>
    
  )
}
